version: "2.0"

session_config:
  session_expiration_time: 60  # value in minutes, 0 means infinitely long
  carry_over_slots_to_new_session: true  # set to false to forget slots between sessions

intents:
  - first
  - greet
  - bye
  - affirmative
  - search_treat
  - search_food
  - search_symptom
  - search_cause
  - search_neopathy
  - search_drug
  - search_prevention
  - search_drug_func
  - search_disease_treat_time
  - search_easy_get
  - search_disease_dept


entities:
  - disease
  - symptom
  - dept
  - drug
  - food


slots:
  disease:
    type: text
    influence_conversation: true
  symptom:
    type: text
    influence_conversation: true
  dept:
    type: text
    influence_conversation: true
  drug:
    type: text
    influence_conversation: true
  food:
    type: text
    influence_conversation: true
  sure:
    type: any
    influence_conversation: false
  pre_disease:
    type: any
    influence_conversation: false


responses:
  utter_first:
    - text: 您好，我是您的医疗助手Friende，我是个机器人，请问有什么可以帮您？
  utter_greet:
    - text: 您好～
    - text: 您好呀～
  utter_goodbye:
    - text: 再见，祝您身体健康～
    - text: 拜拜，希望我有帮到您～
  utter_howcanhelp:
    - text: '您可以这样向我提问: 头痛怎么办/
                              什么人容易头痛/
                              头痛吃什么药/
                              头痛能治吗/
                              头痛属于什么科/
                              头孢地尼分散片用途/
                              如何防止头痛/
                              头痛要治多久/
                              糖尿病有什么并发症/
                              糖尿病有什么症状'
  utter_donknow:
    - text: 啊噢，我没有理解您说的话，我的理解力还需要更多的提升>_<。


actions:
  - utter_first
  - utter_donknow
  - action_first
  - action_donknow
  - action_echo
  - action_search_treat
  - action_search_food
  - action_search_symptom
  - action_search_cause
  - action_search_neopathy
  - action_search_drug
  - action_search_prevention
  - action_search_drug_func
  - action_search_disease_treat_time
  - action_search_easy_get
  - action_search_disease_dept
  - utter_greet
  - utter_howcanhelp
  - utter_goodbye